### PR TITLE
Progressive backoff on trying failed websocket connections on push request

### PR DESCRIPTION
**Pull request by hthetiot**
- [x] Progressive backoff on trying failed websocket connections 
- [x] Update browser test stack for server/client (see #42)
- [ ] Implement connection failure tests

### CODE REVIEW

**Comment by hthetiot** [comment]
See #37

**Comment by dpwspoon** [comment]
LGTM, are you going to add more connection failure tests?  (Checkbox is not currently checked)

**Comment by hthetiot** [comment]
@dpwspoon Yes I want to.

**Comment by hthetiot** [comment]
I will to more complex tests in separate push cause I think this is needed.

**Pull request merged**
